[package]
name = "image-utils"
version = "0.1.1"
authors = ["Anton Smolin"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/embali/image-utils/"
homepage = "https://github.com/embali/image-utils/"
description = """Image processing utilities"""
keywords = ["image", "utils"]
categories = ["multimedia::images"]
exclude = ["tests/images"]

[dependencies]
image = "0.12.3"
gif = "0.9.0"
